### ISSUE TITLE
Support for OS X in `running?`

### ISSUE THREAD

**Issue by tylerjl** [kbsecret/keybase-unofficial-local#1]
In tinkering with kbsecret on OS X, I ran into problems with `Keybase::Local::Config.running?` since OS X lacks the `/proc` filesystem. As far as I can dream up, there aren't many cheap (i.e. non-executing) was to check that Keybase is running on OS X, but removing those lines lets me use kbsecret fully and without problems otherwise.

Should we dig for some alternative method to determine whether Keybase is running, or just omit the check on OS X?

**Comment by woodruffw** [comment]
Some alternative method would be good, I think. `running?` only gets called once or twice per `kbsecret` invocation, so it can be a little expensive. 

IIRC, OS X comes with `pgrep` installed, which would work just fine.

**Comment by woodruffw** [comment]
The commit I just pushed should make `running?` work correctly on OS X. I'll update KBSecret's dependencies later today. Thanks for reporting this!
